on:
  push:
    branches:
      - main
name: Build and Deploy on AWS
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Create a new back-end env file
        uses: SpicyPizza/create-envfile@v1.3.1
        with:
          envkey_PORT: ${{secrets.PORT}}
          envkey_POSTGRES_USERNAME: ${{secrets.POSTGRES_USERNAME}}
          envkey_POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          envkey_POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          envkey_DATABASE_URL: ${{secrets.DATABASE_URL}}
          directory: back-end
          file_name: .env
          fail_on_empty: true
      - name: Create a new front-end env file
        uses: SpicyPizza/create-envfile@v1.3.1
        with:
          envkey_VITE_APP_BACKEND_URL: ${{secrets.VITE_APP_BACKEND_URL}}
          directory: front-end
          file_name: .env
          fail_on_empty: true
      - name: Run docker compose down
        run: docker compose down
      - name: Delete react docker volume
        run: if docker volume ls --quiet --filter name=devops_project_react-volume | grep -q .; then docker volume rm devops_project_react-volume; fi
      - name: Delete ssl docker volume
        run: if docker volume ls --quiet --filter name=devops_project_ssl-certs | grep -q .; then docker volume rm devops_project_ssl-certs; fi
      - name: Build docker images
        run: docker compose build
      - name: Run docker compose
        run: docker compose up -d
